id: P010401
initial_creation_type: ocr
source_metadata:
  id: bdr:W1EE32
  title: ལམ་རིམ་ཆེན་མོ།༼སོག་ཡིག༽
  author: ''
  volumes:
    dfd8e674c69c4bb9bc98e1a79d9b0156:
      image_group_id: I1KG16856
      title: ''
      volume_number: 1
      total_pages: 1126
      base_file: v001.txt
