id: I62583E66
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T00:08:03+00:00'
last_modified: '2022-06-08T13:19:31.712813+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1EE32
  title: ལམ་རིམ་ཆེན་མོ།༼སོག་ཡིག༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C5AB:
      image_group_id: I1KG16856
      title: ''
      total_pages: 1126
      order: 1
      base_file: C5AB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
